coverage:
  status:
    project:
      default:
        target: auto
        threshold: "5%"

    patch:
      default:
        enabled: false

ignore:
  - "crates/seal_macros/**/*"
  - "crates/seal_options_metadata/**/*"
  - "crates/seal_dev/**/*"
  - "crates/seal_logging/**/*"
  - "crates/seal_github/src/github/client.rs"
