coverage:
  status:
    project:
      default:
        target: auto
        threshold: "5%"

    patch:
      default:
        enabled: false

ignore:
  - "crates/seal_macros/**/*"
  - "crates/seal_options_metadata/**/*"
  - "crates/seal_dev/**/*"
