name: Question
description: Ask a question about seal
labels: ["question"]
body:
  - type: textarea
    attributes:
      label: Question
      description: Describe your question in detail.
    validations:
      required: true

  - type: input
    attributes:
      label: Version
      description: What version of seal are you using? (see `seal self version`)
      placeholder: e.g., seal 0.1.0
    validations:
      required: false
